// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3avEH093NPPchn6LkmHpGmIImg8mogA',
    appId: '1:597879774277:web:e1acdfcedaa9964fbd172c',
    messagingSenderId: '597879774277',
    projectId: 'study-stream-ff55c',
    authDomain: 'study-stream-ff55c.firebaseapp.com',
    storageBucket: 'study-stream-ff55c.firebasestorage.app',
    measurementId: 'G-ZVNVGG9GFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_RPhaEIg-7RU7Ziiju_5dgruR5hcdTw',
    appId: '1:597879774277:android:901360e3bdb9dc47bd172c',
    messagingSenderId: '597879774277',
    projectId: 'study-stream-ff55c',
    storageBucket: 'study-stream-ff55c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNlNBEXN2NHpeGGDqnEaRM847pc2Jkys',
    appId: '1:597879774277:ios:2194f855e5dec09cbd172c',
    messagingSenderId: '597879774277',
    projectId: 'study-stream-ff55c',
    storageBucket: 'study-stream-ff55c.firebasestorage.app',
    iosClientId: '597879774277-r3sb38ippr1hog2l4ntt7iln790soejo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNlNBEXN2NHpeGGDqnEaRM847pc2Jkys',
    appId: '1:597879774277:ios:2194f855e5dec09cbd172c',
    messagingSenderId: '597879774277',
    projectId: 'study-stream-ff55c',
    storageBucket: 'study-stream-ff55c.firebasestorage.app',
    iosClientId: '597879774277-r3sb38ippr1hog2l4ntt7iln790soejo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA3avEH093NPPchn6LkmHpGmIImg8mogA',
    appId: '1:597879774277:web:d95abcba60ef4f8ebd172c',
    messagingSenderId: '597879774277',
    projectId: 'study-stream-ff55c',
    authDomain: 'study-stream-ff55c.firebaseapp.com',
    storageBucket: 'study-stream-ff55c.firebasestorage.app',
    measurementId: 'G-BT2E4E0DR8',
  );
}
